import submariner from '@/assets/submariner.jpg';
import royalOak from '@/assets/royal-oak.jpg';
import nautilus from '@/assets/nautilus.jpg';
import speedmaster from '@/assets/speedmaster.jpg';
import subVideo from '@/assets/submariner.webm.asset.json';
import apVideo from '@/assets/royal-oak.webm.asset.json';
import ppVideo from '@/assets/nautilus.webm.asset.json';
import omegaVideo from '@/assets/speedmaster.webm.asset.json';

export type WatchDetails = {
  overview: string; caliber: string; powerReserve: string; frequency: string; jewels: number; winding: string;
  lugWidth: string; caseMaterial: string; caseback: string; dialFinish: string; crystal: string; bezelDetail: string;
  bracelet: string; clasp: string; waterDetail: string;
};

export type Watch = {
  id: string; brand: string; model: string; ref: string; year: number; image: string; video: string;
  creator: string; initials: string; caption: string; tags: string; likes: number; comments: number; saves: number;
  wrist: number; diameter: number; thickness: number; lug: string; movement: string; type: string;
  reserve: number; vph: string; dial: string; bezel: string; water: string; retail: number; market: number; category: string[]; details: WatchDetails;
  music?: { title: string; artist: string };
  is_live_verified?: boolean; foundingMember?: boolean;
  auction?: { highest: number; count: number; increment: number; seconds: number } | undefined;
  edit?: { kind: 'video' | 'photo'; aspect: string; cssFilter: string; vignette: number; text?: string; textStyle?: string; trim?: [number, number]; originalVolume: number; bgmVolume: number };
};
export const watches: [Watch, Watch, Watch, Watch] = [
  { id:'rolex', brand:'Rolex', model:'Submariner Date', ref:'126610LN', year:2020, image:submariner, video:subVideo.url,
    creator:'the.wrist.diary', initials:'JD', caption:'Some things don’t need an introduction.\nThe everyday icon, up close.', tags:'#Rolex #Submariner #WOTD', likes:2480, comments:128, saves:346,
    wrist:16.5, diameter:41, thickness:12, lug:'48.1', movement:'Caliber 3235', type:'Automatic', reserve:70, vph:'28,800', dial:'Black', bezel:'Cerachrom ceramic', water:'300m / 1,000 ft', retail:10250, market:14200, category:['Rolex','Lume Shots'], details: {"overview": "First introduced in 1953, the Rolex Submariner helped define the modern professional dive watch. The Submariner Date pairs robust Oystersteel construction with an instantly recognizable black ceramic bezel and a highly legible Chromalight dial. Equally at home beneath the waves or beneath a shirt cuff, it remains an enduring expression of functional luxury.", "caliber": "In-house Caliber 3235 (Automatic)", "powerReserve": "Approximately 70 hours", "frequency": "28,800 vph (4 Hz)", "jewels": 31, "winding": "Bidirectional self-winding via Perpetual rotor", "lugWidth": "21 mm", "caseMaterial": "Oystersteel (904L stainless steel)", "caseback": "Solid screw-down caseback", "dialFinish": "Gloss black with Chromalight long-lasting blue luminescence", "crystal": "Scratch-resistant sapphire with Cyclops lens over the date", "bezelDetail": "Unidirectional rotatable, 60-minute graduated bezel with black Cerachrom ceramic insert", "bracelet": "Oyster bracelet, flat three-piece links in Oystersteel", "clasp": "Folding Oysterlock safety clasp with Rolex Glidelock extension system", "waterDetail": "300 metres / 1,000 feet; screw-down Triplock crown with triple waterproofness system"} },
  { id:'ap', brand:'Audemars Piguet', model:'Royal Oak', ref:'15510ST', year:2022, image:royalOak, video:apVideo.url,
    creator:'eight.screws', initials:'ES', caption:'Fifty years of breaking the rules.\nEvery brushed edge tells a story.', tags:'#RoyalOak #Tapisserie #WOTD', likes:3820, comments:94, saves:502,
    wrist:17, diameter:41, thickness:10.5, lug:'51.5', movement:'Caliber 4302', type:'Automatic', reserve:70, vph:'28,800', dial:'Blue', bezel:'Stainless steel', water:'50m / 165 ft', retail:28000, market:42000, category:['Complications'], details: {"overview": "Designed by Gérald Genta and introduced in 1972, the Royal Oak challenged luxury-watch conventions with a steel case, exposed bezel screws and an integrated bracelet. The 15510ST continues that architectural language with a blue Grande Tapisserie dial and carefully alternating brushed and polished surfaces. Its sapphire caseback reveals the in-house Caliber 4302, bringing contemporary mechanics to a design icon.", "caliber": "In-house Caliber 4302 (Automatic)", "powerReserve": "Approximately 70 hours", "frequency": "28,800 vph (4 Hz)", "jewels": 32, "winding": "Bidirectional self-winding via 22-carat gold oscillating weight", "lugWidth": "Integrated bracelet; proprietary case attachment", "caseMaterial": "Stainless steel with brushed and polished finishing", "caseback": "Sapphire exhibition caseback", "dialFinish": "Bleu Nuit, Nuage 50 Grande Tapisserie with white-gold markers and luminescent coating", "crystal": "Glareproofed sapphire crystal and caseback", "bezelDetail": "Fixed octagonal stainless-steel bezel with eight white-gold screws", "bracelet": "Integrated stainless-steel bracelet with brushed links and polished bevels", "clasp": "AP folding clasp", "waterDetail": "50 metres / 165 feet; screw-locked crown"} },
  { id:'patek', brand:'Patek Philippe', model:'Nautilus', ref:'5711/1A-014', year:2021, image:nautilus, video:ppVideo.url,
    creator:'caliber.collective', initials:'CC', caption:'An olive-green farewell.\nA little piece of horological history.', tags:'#PatekPhilippe #Nautilus #GreenDial', likes:5120, comments:203, saves:780,
    wrist:16.8, diameter:40, thickness:8.3, lug:'44.5', movement:'Caliber 26-330 S C', type:'Automatic', reserve:45, vph:'28,800', dial:'Green', bezel:'Stainless steel', water:'120m / 400 ft', retail:34893, market:185000, category:['Vintage'], details: {"overview": "Introduced in 1976, the Gérald Genta-designed Nautilus brought a porthole-inspired case and integrated steel bracelet to Patek Philippe’s world of refined watchmaking. The 2021 reference 5711/1A-014 gave the celebrated silhouette an olive-green sunburst dial for the final chapter of the steel 5711. Beneath its slender profile, the Caliber 26-330 S C combines traditional finishing with practical stop-seconds precision.", "caliber": "In-house Caliber 26-330 S C (Automatic)", "powerReserve": "Minimum 35 hours / maximum 45 hours", "frequency": "28,800 vph (4 Hz)", "jewels": 30, "winding": "Unidirectional self-winding via central 21-carat gold rotor", "lugWidth": "Integrated bracelet; proprietary case attachment", "caseMaterial": "Stainless steel with satin-brushed and polished finishing", "caseback": "Sapphire exhibition caseback", "dialFinish": "Olive-green sunburst, horizontally embossed; gold applied markers with luminescent coating", "crystal": "Sapphire crystal and sapphire-crystal caseback", "bezelDetail": "Fixed rounded-octagonal stainless-steel bezel with satin-brushed face and polished edges", "bracelet": "Integrated stainless-steel bracelet with polished centre links", "clasp": "Fold-over clasp", "waterDetail": "120 metres / 400 feet as originally specified for this reference; screw-down crown"} },
  { id:'omega', brand:'Omega', model:'Speedmaster Professional', ref:'310.30.42.50.01.002', year:2021, image:speedmaster, video:omegaVideo.url,
    creator:'moonwatch.journal', initials:'MJ', caption:'Flight-qualified. Earth-approved.\nThe view through the sapphire is everything.', tags:'#Speedmaster #Moonwatch #MovementFriday', likes:1920, comments:76, saves:294,
    wrist:18, diameter:42, thickness:13.2, lug:'47.5', movement:'Caliber 3861', type:'Manual', reserve:50, vph:'21,600', dial:'Black', bezel:'Aluminum tachymeter', water:'50m / 165 ft', retail:8000, market:6800, category:['Vintage','Complications','Lume Shots'], details: {"overview": "Born in 1957, the Speedmaster became a space-exploration icon when it accompanied astronauts onto the lunar surface in 1969. This sapphire Moonwatch carries forward the asymmetrical case, stepped black dial and famous tachymeter bezel while showcasing its movement through an exhibition back. The hand-wound Caliber 3861 adds Co-Axial escapement technology and Master Chronometer certification to that storied lineage.", "caliber": "Caliber 3861 (Manual, Co-Axial Master Chronometer)", "powerReserve": "Approximately 50 hours", "frequency": "21,600 vph (3 Hz)", "jewels": 26, "winding": "Manual winding via crown; no automatic rotor", "lugWidth": "20 mm", "caseMaterial": "Stainless steel, asymmetrical case with crown guards", "caseback": "Sapphire exhibition caseback with Moonwatch engravings", "dialFinish": "Stepped black dial with applied Omega logo and Super-LumiNova hands and markers", "crystal": "Scratch-resistant sapphire with anti-reflective treatment on the inner surface", "bezelDetail": "Fixed black anodised aluminium tachymeter bezel with dot over 90", "bracelet": "Stainless-steel bracelet with five-arched-links-per-row design", "clasp": "Folding clasp with comfort setting", "waterDetail": "50 metres / 165 feet; push-pull crown"} },
];
export const categories = ['For You','Rolex','Vintage','Microbrands','Complications','Lume Shots'];
export const money = (value: number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
export const compact = (value: number) => value >= 1000 ? `${(value/1000).toFixed(1)}K` : `${value}`;
export const pageHead = (title: string, description: string) => ({meta:[{title:`${title} — WRISTORY`},{name:'description',content:description},{property:'og:title',content:`${title} — WRISTORY`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]});