import { useEffect, useRef, useState } from 'react';
import { Upload, ScanLine, Check, ArrowUpRight, Film, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { BottomSheet } from './sheets';
import { useCommunity } from './store';
import { watches } from './data';
export function UploadSheet(){
 const {uploadOpen,closeUpload,addUpload}=useCommunity();const [file,setFile]=useState<File|null>(null);const [progress,setProgress]=useState(0);const [caption,setCaption]=useState('A closer look at my everyday companion. #WOTD');const input=useRef<HTMLInputElement>(null);const [error,setError]=useState('');
 const choose=(next?:File)=>{if(!next)return;if(!next.type.startsWith('video/')){setError('Please select a video file.');return;}if(next.size>200*1024*1024){setError('Please choose a video smaller than 200 MB.');return;}setError('');setFile(next);setProgress(0)};
 useEffect(()=>{if(!file||!uploadOpen)return;const timer=setInterval(()=>setProgress(p=>Math.min(100,p+5)),130);return()=>clearInterval(timer)},[file,uploadOpen]);
 const base=watches[0];
 return <BottomSheet open={uploadOpen} onClose={closeUpload} title="Share your wrist story"><div className="upload-content"><p className="subtle">A moment. A movement. Your perspective.</p><input hidden ref={input} type="file" accept="video/*" onChange={e=>choose(e.target.files?.[0])}/><Button variant="dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}>{file?<Film/>:<Upload/>}<strong>{file?file.name:'Drop your watch video here'}</strong><span>{file?'Choose a different video':'or browse files · MP4, MOV · up to 200 MB'}</span></Button>{error&&<p role="alert" className="error-text">{error}</p>}{file&&<><div className="scanner"><div><ScanLine/><span>{progress<100?'Recognizing your timepiece…':'Timepiece recognized'}</span><strong>{progress}%</strong></div><progress max="100" value={progress}/><small><Sparkles size={12}/> Simulated AI frame recognition</small></div>{progress===100&&<><div className="scan-results">{[['Brand',base.brand],['Model',base.model],['Reference',base.ref],['Wrist size','16.5 cm']].map(([label,value])=><label key={label}>{label}<input aria-label={label} defaultValue={value}/></label>)}</div><label className="caption-input">Caption<textarea aria-label="Video caption" value={caption} onChange={e=>setCaption(e.target.value)}/></label><Button className="w-full" onClick={()=>{const fields=document.querySelectorAll<HTMLInputElement>('.scan-results input');addUpload({...base,id:`upload-${Date.now()}`,brand:fields[0]?.value||base.brand,model:fields[1]?.value||base.model,ref:fields[2]?.value||base.ref,wrist:parseFloat(fields[3]?.value||'16.5')||16.5,creator:'alex.morgan',initials:'AM',caption,video:URL.createObjectURL(file)});setFile(null);setProgress(0);closeUpload()}}><Check/> Add to my watchbox <ArrowUpRight/></Button><p className="market-note">Preview only · this upload stays in your current session.</p></> }</>}</div></BottomSheet>;
}
