/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActiveBidsRouteImport } from './routes/active-bids'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as WatchboxRouteImport } from './routes/watchbox'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveBidsRoute = ActiveBidsRouteImport.update({
  id: '/active-bids',
  path: '/active-bids',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchboxRoute = WatchboxRouteImport.update({
  id: '/watchbox',
  path: '/watchbox',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-bids': typeof ActiveBidsRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/watchbox': typeof WatchboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-bids': typeof ActiveBidsRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/watchbox': typeof WatchboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-bids': typeof ActiveBidsRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/profile': typeof ProfileRoute
  '/watchbox': typeof WatchboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/active-bids' | '/chat' | '/discover' | '/profile' | '/watchbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/active-bids' | '/chat' | '/discover' | '/profile' | '/watchbox'
  id:
    | '__root__'
    | '/'
    | '/active-bids'
    | '/chat'
    | '/discover'
    | '/profile'
    | '/watchbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveBidsRoute: typeof ActiveBidsRoute
  ChatRoute: typeof ChatRoute
  DiscoverRoute: typeof DiscoverRoute
  ProfileRoute: typeof ProfileRoute
  WatchboxRoute: typeof WatchboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-bids': {
      id: '/active-bids'
      path: '/active-bids'
      fullPath: '/active-bids'
      preLoaderRoute: typeof ActiveBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchbox': {
      id: '/watchbox'
      path: '/watchbox'
      fullPath: '/watchbox'
      preLoaderRoute: typeof WatchboxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveBidsRoute: ActiveBidsRoute,
  ChatRoute: ChatRoute,
  DiscoverRoute: DiscoverRoute,
  ProfileRoute: ProfileRoute,
  WatchboxRoute: WatchboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
